export const SYSTEM_CONSTANTS = {
  CHANNELS: ['WHATSAPP', 'INSTAGRAM', 'MESSENGER'] as const,
  LEAD_STATUS: {
    QUALIFIED: 'QUALIFIED',
    PENDING: 'PENDING',
    CONVERTED: 'CONVERTED'
  },
  DEFAULT_CACHING_MAX_AGE_SEC: 300,
};